#!/bin/bash
## echo "writing automated test"


if [[ $1 = "ga" ]]
then
	git add .

elif [[ $1 = "gc" ]] && [[ -n $2 ]]
then
	git add . 
	git commit -m $2

elif [[ $1 = "gp" ]] && [[ -n $2 ]]
then
	git add .
	git commit -m $2
	git push

elif [[ $1 = "p" ]]
then
	git push

elif [[ $1 = "s" ]]
then
	npm run dev

elif [[ $1 = "f" ]]
then 
	npx prettier . --write

elif [[ $1 = "c" ]]
then
	npx prettier . --check

elif [[ $1 = "gfp" ]] && [[ -n $2 ]]
then
	npx prettier . --write
	git add .
	git commit -m $2
	git push

elif [[ $1 = "style" ]]
then
	sass --style=compressed -w src/scss:dist

else
	echo "./auto [option1] [option2]"
	echo "
	ga = git add .

	gc = git add and commit [option2]

	gp = git add/commit and push

	p = just push

	s = start server

	f = format code

	c = check code quality

	gfp = format before pushing

	style = compile sass to css "

fi
